// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

uint8_t count_press = 0;
void buttonPress(lv_event_t * e)
{
	// Your code here
	// change label text
	uint8_t buffer_text[20];
	sprintf((char *)buffer_text, "count %d", count_press);
	count_press++;
	lv_label_set_text(ui_Label1, buffer_text);

}
